### PR TITLE
Fix NullReferenceException in Analyzer

### LINKED ISSUE #2398: ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer null reference exception in .NET 7
### Description

Compiling this project - https://github.com/grpc/grpc-dotnet/tree/master/src/Grpc.AspNetCore.Server - with .NET 7 alpha results in an error from an analyzer:

```
Microsoft (R) Build Engine version 17.1.0-preview-21567-01+7434b575d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.Net.Common/Grpc.Net.Common.csproj (in 5.99 sec).
  Restored /tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj (in 6.61 sec).
  Restored /tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/perf/benchmarkapps/GrpcAspNetCoreServer/GrpcAspNetCoreServer.csproj (in 8.17 sec).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
/root/.nuget/packages/microsoft.codeanalysis.netanalyzers/6.0.0/build/Microsoft.CodeAnalysis.NetAnalyzers.targets(591,5): warning : The .NET SDK has newer analyzers with version '7.0.0' than what version '6.0.0' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.Net.Common/Grpc.Net.Common.csproj]
  Grpc.Net.Common -> /tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.Net.Common/bin/Release/net6.0/Grpc.Net.Common.dll
/root/.nuget/packages/microsoft.codeanalysis.netanalyzers/6.0.0/build/Microsoft.CodeAnalysis.NetAnalyzers.targets(591,5): warning : The .NET SDK has newer analyzers with version '7.0.0' than what version '6.0.0' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
CSC : error AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/tmp/benchmarks-agent/benchmarks-server-1/k4xahm5y.iun/grpc-dotnet/src/Grpc.AspNetCore.Server/Grpc.AspNetCore.Server.csproj]
Exit code: 1

[01:32:34.918] Job has failed, interrupting benchmarks ...
[01:32:34.921] Stopping job 'application' ...
[01:32:35.947] Deleting job 'application' ...

| application           |                               |   |
| --------------------- | ----------------------------- | - |
| .NET Core SDK Version | 7.0.100-alpha.1.21568.2       |   |
| ASP.NET Core Version  | 7.0.0-alpha.1.21574.6+8817967 |   |
| .NET Runtime Version  | 7.0.0-alpha.1.21575.3+db6f5ce |   |
```

I'm not sure where this code is located. Please move to the right repo if this isn't the right place.

### Reproduction Steps

The error happens when [grpc-dotnet](https://github.com/grpc/grpc-dotnet) is benchmarked in the ASP.NET Core benchmark environment using .NET 7.

I haven't attempted to reproduce it locally, but I suspect using .NET 7 SDK and updating the project to net7 will cause the same error.

### Expected behavior

Compile successfully.

### Actual behavior

See error above.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tlakollo**
Fix NullReferenceException in Analyzer by checking the containing type is not null before using it
Fixes #2398

### CODE REVIEW

**Comment by vitek-karas** [comment]
What is the code pattern that triggers this? Can we add a test?

**Comment by tlakollo** [comment]
> What is the code pattern that triggers this? Can we add a test?

Along with Andy we came up with some theories and then I went ahead and reproduce the issue to see if the theory hold up. The problem is when checking field references. If there is a field reference on a top-level class we would get the containing symbol which is the top-level class and then we would ask if this symbol has attributes or if the containingType of the containing symbol has attributes. By this moment the ContainingType is null. 

For example:

```C#
namespace Grpc.AspNetCore.Server.Internal
{
    internal partial class ServerCallHandlerFactory<[DynamicallyAccessedMembers(GrpcProtocolConstants.ServiceAccessibility)] TService> where TService : class
    { ... }
}
```
We analyze the field access to ServiceAccesibility, we figure out that the ContainingSymbol is the class ServerCallHandlerFactory, and then we ask if this class has RUC and then if the ContainingType (null) has attributes.

I will add a test in the linker with something similar

**Comment by vitek-karas** [comment]
Does it mean that the better way to fix this would be to not look for containing type if the current symbol is a type already? RUC on type doesn't propagate onto nested classes, so once we find a parent type, that's the last place to check.

**Comment by tlakollo** [comment]
I added a test in the analyzer but it's in a strange place because it won't verify the fix until https://github.com/dotnet/linker/issues/2404 gets fixed. At this moment the test won't fail nor throw the exceptions generated during testing.

File: src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs [hunk 1]
```diff
@@ -341,15 +341,16 @@ private void ReportMismatchInAttributesDiagnostic (SymbolAnalysisContext symbolA
 		/// <summary>
 		/// True if the source of a call is considered to be annotated with the Requires... attribute
 		/// </summary>
-		protected bool IsMemberInRequiresScope (ISymbol containingSymbol)
+		protected bool IsMemberInRequiresScope (ISymbol member)
 		{
-			if (containingSymbol.HasAttribute (RequiresAttributeName) ||
-				containingSymbol.ContainingType.HasAttribute (RequiresAttributeName)) {
+			if (member.HasAttribute (RequiresAttributeName) ||
+				member is not ITypeSymbol &&
```
Comment (vitek-karas) [inline src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs:347]: Nit - I would prefer parenthesis around the `( && )` I know that this works, but I think it would be more readable that way.

**Review by vitek-karas — APPROVED** [review]

File: src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs (hunk 1 above)
Comment (tlakollo) [reply src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs:347]: I will add parenthesis to both Analyzer and linker
